services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "ITCronTestTask"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  itcrontesttask.api:
    container_name: itcrontesttask.api
    image: itcrontesttask.api
    build:
      context: .
      dockerfile: ITCronTestTask.API/Dockerfile
    environment:
      - ConnectionStrings__IpInfoDbContext=User ID=postgres;Password=123;Host=postgres;Port=5432;Database=ITCronTestTask;
    ports:
      - "28000:8080"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - app-network

volumes: 
  postgres-data:
networks:
  app-network: