services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "ITCronTestTask"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
#  itcrontesttask.api:
#    image: itcrontesttask.api
#    build:
#      context: .
#      dockerfile: ITCronTestTask.API/Dockerfile

volumes: 
  postgres-data: